FROM        debian:bookworm-slim

## Configura o sistema para arquitetura i386
RUN dpkg --add-architecture i386

## Atualiza e instala pacotes necessários
RUN apt update && \
    apt install -y --no-install-recommends \
        wget \
        nohub \
        lib32stdc++6 \
        libc6-i386 \
        lib32gcc-s1 \
        iproute2 \
        gnupg2 \
        software-properties-common \
        libntlm0 \
        winbind \
        xvfb \
        xauth \
        libncurses5-dev:i386 \
        libncurses6 \
        dbus \
        libgdiplus \
        lib32gcc-s1 \
        alsa-tools \
        libpulse0 \
        pulseaudio \
        libpulse-dev \
        libasound2 \
        libao-common \
        gnutls-bin \
        locales \
        numactl \
        cabextract \
        curl \
        python3 \
        python3-pip \
        python3-setuptools \
        tini \
        file \
        pipx \
        tar \
        gcc \
        g++ \
        libgcc-11-dev \
        libgcc-12-dev \
        libcurl4-gnutls-dev:i386 \
        libssl-dev:i386 \
        libcurl4:i386 \
        lib32tinfo6 \
        libtinfo6:i386 \
        lib32z1 \
        libncurses5:i386 \
        libcurl3-gnutls:i386 \
        libsdl2-2.0-0:i386 \
        gdb \
        libsdl1.2debian \
        libfontconfig1 \
        telnet \
        net-tools \
        netcat-traditional \
        tzdata && \
    apt upgrade -y

## Cria o usuário container
RUN useradd -m -d /home/container container

## install rcon
RUN         cd /tmp/ \
            && curl -sSL https://github.com/gorcon/rcon-cli/releases/download/v0.10.3/rcon-0.10.3-amd64_linux.tar.gz > rcon.tar.gz \
            && tar xvf rcon.tar.gz \
            && mv rcon-0.10.3-amd64_linux/rcon /usr/local/bin/

# Temp fix for things that still need libssl1.1
RUN     if [ "$(uname -m)" = "x86_64" ]; then \
    wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb && \
    dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb && \
    rm libssl1.1_1.1.0g-2ubuntu4_amd64.deb; \
fi

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

STOPSIGNAL SIGINT

COPY        --chown=container:container ./../entrypoint.sh /entrypoint.sh
RUN         chmod +x /entrypoint.sh
ENTRYPOINT  ["/bin/bash", "-g", "--"]
CMD         ["/entrypoint.sh"]
