# Define a imagem base
FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive

# Instala dependências
RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake git unzip build-essential ca-certificates curl zip tar \
    pkg-config ninja-build autoconf automake libtool \
    python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Define o usuário padrão e o diretório de trabalho
USER container
ENV USER=container HOME=/home/container
WORKDIR /home/container

# Copia o script de entrada para o contêiner e define como comando padrão
COPY ./entrypoint.sh /entrypoint.sh
CMD ["/bin/bash", "/entrypoint.sh"]
