FROM alpine:3.14

RUN apk --update --no-cache add curl ca-certificates nginx git

ENV PHP_VERSION="7"
ENV PHP_DEPENDENCIES="ctype,json,posix,zlib,fileinfo,ftp,pcntl,phar,fpm,dom,xml,simplexml,mbstring,xmlwriter,xmlreader,pdo_mysql,mysqli,bcmath,bz2,curl,gd,opcache,gmp,imap,intl,ldap,sodium,zip,exif,session,soap,openssl,pdo_odbc,pdo,odbc,gettext,iconv,tokenizer"

# Create a single command to install PHP and dependencies
RUN PHP_CMD="php${PHP_VERSION}"; \
    for dep in ${PHP_DEPENDENCIES//,/ }; do \
        PHP_CMD+=" php${PHP_VERSION}-$dep"; \
    done; \
    echo "**** PHP Installation ${PHP_VERSION} ****" && \
    apk update && \
    apk add --no-cache --update $PHP_CMD && \
    rm -rf /var/cache/apk/*

RUN php${PHP_VERSION} -v
    
COPY --from=composer:latest  /usr/bin/composer /usr/bin/composer
RUN apk add --no-cache --upgrade bash
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

USER container
ENV USER container
ENV HOME /home/container
ENV SHELL /bin/bash

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
