FROM alpine:latest
RUN apk --update --no-cache add curl ca-certificates bash nginx

ENV PHP_VERSION="74"
ARG PHP_DEPENDENCIES="ctype,json,posix,zlib,fileinfo,ftp,pcntl,phar,fpm,dom,xml,simplexml,mbstring,xmlwriter,xmlreader,pdo_mysql,mysqli,bcmath,bz2,curl,gd,opcache,gmp,imap,intl,ldap,sodium,zip,exif,session,soap,openssl,pdo_odbc,pdo,odbc,gettext,iconv,tokenizer"

RUN PHP_CMD="php${PHP_VERSION}"
RUN for dep in $(echo ${PHP_DEPENDENCIES} | tr ',' ' '); do \
        PHP_CMD="$PHP_CMD php${PHP_VERSION}-$dep"; \
    done

RUN echo "**** PHP Installation ${PHP_VERSION} ****" && \
    apk update && \
    apk add --no-cache --update $PHP_CMD && \
    rm -rf /var/cache/apk/*

RUN php${PHP_VERSION} -v
    
COPY --from=composer:latest  /usr/bin/composer /usr/bin/composer

USER container
ENV USER container
ENV HOME /home/container
ENV SHELL /bin/bash

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
