FROM alpine:3.14

RUN apk --update --no-cache add curl ca-certificates nginx git

ENV PHP_VERSION="7"

RUN apk update && \
    apk add --no-cache --update \
        php${PHP_VERSION} \
        php${PHP_VERSION}-ctype \
        php${PHP_VERSION}-json \
        php${PHP_VERSION}-posix \
        php${PHP_VERSION}-zlib \
        php${PHP_VERSION}-fileinfo \
        php${PHP_VERSION}-ftp \
        php${PHP_VERSION}-pcntl \
        php${PHP_VERSION}-phar \
        php${PHP_VERSION}-fpm \
        php${PHP_VERSION}-dom \
        php${PHP_VERSION}-xml \
        php${PHP_VERSION}-simplexml \
        php${PHP_VERSION}-mbstring \
        php${PHP_VERSION}-xmlwriter \
        php${PHP_VERSION}-xmlreader \
        php${PHP_VERSION}-pdo_mysql \
        php${PHP_VERSION}-mysqli \
        php${PHP_VERSION}-bcmath \
        php${PHP_VERSION}-bz2 \
        php${PHP_VERSION}-curl \
        php${PHP_VERSION}-gd \
        php${PHP_VERSION}-opcache \
        php${PHP_VERSION}-gmp \
        php${PHP_VERSION}-imap \
        php${PHP_VERSION}-intl \
        php${PHP_VERSION}-ldap \
        php${PHP_VERSION}-sodium \
        php${PHP_VERSION}-zip \
        php${PHP_VERSION}-exif \
        php${PHP_VERSION}-session \
        php${PHP_VERSION}-soap \
        php${PHP_VERSION}-openssl \
        php${PHP_VERSION}-pdo_odbc \
        php${PHP_VERSION}-pdo \
        php${PHP_VERSION}-odbc \
        php${PHP_VERSION}-gettext \
        php${PHP_VERSION}-iconv \
        php${PHP_VERSION}-tokenizer && \
    rm -rf /var/cache/apk/*

RUN php${PHP_VERSION} -v
    
COPY --from=composer:latest  /usr/bin/composer /usr/bin/composer
RUN apk add --no-cache --upgrade bash
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

USER container
ENV USER container
ENV HOME /home/container
ENV SHELL /bin/bash

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
