FROM alpine:3.17

RUN echo "**** Instalando ****" && \
    apk --update --no-cache add curl ca-certificates nginx && \
    apk add --no-cache --upgrade sudo git curl tar && \
    apk --update add git curl file unzip tar wget && \
    apk add util-linux && \
    apk update

USER container
ENV USER container
ENV HOME /home/container

WORKDIR /home/container

COPY entrypoint.sh /entrypoint.sh

CMD ["/bin/ash", "/entrypoint.sh"]
