FROM ubuntu:jammy

RUN apt update \
    && apt -y upgrade
RUN dpkg --add-architecture i386 \
    && apt update \
    && apt upgrade -y \
    && apt install -y libstdc++6 lib32stdc++6 tar curl iproute2 openssl fontconfig dirmngr ca-certificates dnsutils tzdata zip \
    && apt install -y libtbb2:i386 libtbb-dev:i386 libicu-dev:i386 samba \
    && useradd -d /home/container -m container

# Cria o diretório usershares no home do container e configura permissões
RUN mkdir -p /home/container/samba/usershares \
    && chown container:container /home/container/samba/usershares \
    && chmod 1770 /home/container/samba/usershares

# Configura o Samba para usar o novo path (como root, antes de mudar para USER container)
RUN echo -e "[global]\nusershare path = /home/container/samba/usershares" >> /etc/samba/smb.conf

RUN mkdir -p /run/systemd && echo 'docker' > /run/systemd/container
RUN rm -rf /var/lib/apt/lists/*

USER container
ENV USER=container HOME=/home/container
WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh
CMD ["/bin/bash", "/entrypoint.sh"]