FROM alpine:latest

RUN apk update

RUN apk add --no-cache --upgrade \
    gcc g++ libgcc libc-dev gdb libc6-compat git wget curl tar zip unzip binutils xz lzo cabextract iproute2 net-tools netcat-openbsd busybox-extras libatomic sdl2 \
    fontconfig icu-libs icu-dev libunwind openssl-dev sqlite sqlite-dev mariadb-dev duktape libzip tzdata ffmpeg \
    gnutls jsoncpp leveldb lua-dev luajit-dev sqlite-libs fluidsynth bzip2 zlib-dev libevent-dev \
    samba samba-common-tools smbnetfs

RUN echo "America/Sao_Paulo" >  /etc/timezone

ENV TZ America/Sao_Paulo
ENV LANG pt_BR.UTF-8
ENV LANGUAGE pt_BR.UTF-8
ENV LC_ALL pt_BR.UTF-8

RUN apk add --no-cache --upgrade bash

RUN rm /bin/sh && ln -s /bin/bash /bin/sh
 
USER container
ENV  USER container
ENV HOME /home/container

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]