# Usando a imagem base do CentOS
FROM centos:8

LABEL author="Drylian" maintainer="danielolxlol@gmail.com"

# Definir a versão do PHP
ENV PHP_VERSION=8.2

# Atualizar o sistema e instalar dependências
RUN dnf -y update && \
    dnf -y install \
    epel-release && \
    dnf -y install \
    php${PHP_VERSION} \
    php${PHP_VERSION}-bcmath \
    php${PHP_VERSION}-cli \
    php${PHP_VERSION}-common \
    php${PHP_VERSION}-dom \
    php${PHP_VERSION}-curl \
    php${PHP_VERSION}-intl \
    php${PHP_VERSION}-fileinfo \
    php${PHP_VERSION}-fpm \
    php${PHP_VERSION}-gd \
    php${PHP_VERSION}-mbstring \
    php${PHP_VERSION}-mysqli \
    php${PHP_VERSION}-pdo \
    php${PHP_VERSION}-pdo_mysql \
    php${PHP_VERSION}-phar \
    php${PHP_VERSION}-posix \
    php${PHP_VERSION}-session \
    php${PHP_VERSION}-simplexml \
    php${PHP_VERSION}-sodium \
    php${PHP_VERSION}-tokenizer \
    php${PHP_VERSION}-xml \
    php${PHP_VERSION}-zip \
    php${PHP_VERSION}-sockets \
    php${PHP_VERSION}-ctype \
    wget \
    curl \
    git \
    nginx \
    && dnf clean all

# Copiar o script do Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Instalar o Bash
RUN dnf -y install bash

# Definir o timezone
RUN echo "UTC" > /etc/timezone

# Copiar o script de crontab
COPY ./crontab_test.sh /
RUN chmod +x /crontab_test.sh

# Criar usuário e definir o diretório de trabalho
RUN useradd -ms /bin/bash container
USER container
ENV USER=container
ENV HOME=/home/container
WORKDIR /home/container

# Copiar o script de entrada
COPY ./entrypoint.sh /entrypoint.sh

# Definir o comando padrão
CMD ["/bin/bash", "/entrypoint.sh"]
