FROM ubuntu:22.04

LABEL author="Alternight Drylian" maintainer="danielolxlol@gmail.com"

ENV   DEBIAN_FRONTEND noninteractive

## add container user
RUN   useradd -m -d /home/container -s /bin/bash container

# Instale as dependências necessárias (se houver)
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    libmfx1 \
    libboost-filesystem1.74.0 \
    libboost-locale1.74.0 \
    libboost-log1.74.0 \
    libboost-program-options1.74.0 \
    libboost-thread1.74.0 \
    libdrm2 \
    libevdev2 \
    libnuma1 \
    libopus0 \
    libpulse0 \
    libva2 \
    libva-drm2 \
    libvdpau1 \
    libwayland-client0 \
    libx11-6 \
    libappindicator3-1 \
    # Outras dependências, se necessário \
    && rm -rf /var/lib/apt/lists/*

# Baixe o pacote Sunshine .deb
RUN wget https://github.com/LizardByte/Sunshine/releases/download/v0.20.0/sunshine-ubuntu-22.04-amd64.deb

# Instale o pacote Sunshine .deb
RUN dpkg -i sunshine-ubuntu-22.04-amd64.deb

# Se desejar, limpe os arquivos temporários
RUN rm sunshine-ubuntu-22.04-amd64.deb

# Defina os comandos ou ações padrão que devem ser executados quando um contêiner é iniciado
WORKDIR /home/container

COPY  ./entrypoint.sh /entrypoint.sh
CMD   [ "/bin/bash", "/entrypoint.sh" ]
