name: build Chromium
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - chromium/**
jobs:
  push:
    name: "chromium:${{ matrix.game }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game:
          - "18"
          - "20"
          - "22"
          - "23"
          - "24"
          
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: ./chromium
          file: ./chromium/${{ matrix.game }}/dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/drylian/chromium:${{ matrix.game }}
