name: Build PHP Versions
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - PHP/**

jobs:
  push:
    name: "Build and push PHP images"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          driver-opts: |
            image=moby/buildkit:v0.12.0

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: ./PHP/${{ matrix.php }}
          file: ./PHP/${{ matrix.php }}/dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/drylian/php:${{ matrix.php }}
