name: build Tibia
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - ConterStrike/**
jobs:
  push:
    name: "steamcmd:${{ matrix.game }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game:
          - server
          
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: ./ConterStrike/${{ matrix.game }}
          file: ./ConterStrike/${{ matrix.game }}/dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/drylian/steamcmd:${{ matrix.game }}
