name: build Games
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - system/**
jobs:
  push:
    name: "system:${{ matrix.system }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        system:
          - samba

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: ./system/${{ matrix.system }}
          file: ./system/${{ matrix.system }}/dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/drylian/system:${{ matrix.system }}